This exercise will require you to pull some data from the Qunadl API. Qaundl is currently the most widely used aggregator of financial market data.

As a first step, you will need to register a free account on the http://www.quandl.com website.

After you register, you will be provided with a unique API key, that you should store:

In [ ]:
# Store the API key as a string - according to PEP8, constants are always named in all upper case
API_KEY = 'WFJLtaGfefmVvsDu7iG8'

Qaundl has a large number of data sources, but, unfortunately, most of them require a Premium subscription. Still, there are also a good number of free datasets.

For this mini project, we will focus on equities data from the Frankfurt Stock Exhange (FSE), which is available for free. We'll try and analyze the stock prices of a company called Carl Zeiss Meditec, which manufactures tools for eye examinations, as well as medical lasers for laser eye surgery: https://www.zeiss.com/meditec/int/home.html. The company is listed under the stock ticker AFX_X.

You can find the detailed Quandl API instructions here: https://docs.quandl.com/docs/time-series

While there is a dedicated Python package for connecting to the Quandl API, we would prefer that you use the *requests* package, which can be easily downloaded using *pip* or *conda*. You can find the documentation for the package here: http://docs.python-requests.org/en/master/

Finally, apart from the *requests* package, you are encouraged to not use any third party Python packages, such as *pandas*, and instead focus on what's available in the Python Standard Library (the *collections* module might come in handy: https://pymotw.com/3/collections/).
Also, since you won't have access to DataFrames, you are encouraged to us Python's native data structures - preferably dictionaries, though some questions can also be answered using lists.
You can read more on these data structures here: https://docs.python.org/3/tutorial/datastructures.html

Keep in mind that the JSON responses you will be getting from the API map almost one-to-one to Python's dictionaries. Unfortunately, they can be very nested, so make sure you read up on indexing dictionaries in the documentation provided above.

In [103]:
# First, import the relevant modules
import json
import requests
import pandas as pd
from pandas.io.json import json_normalize

In [104]:
# Now, call the Quandl API and pull out a small sample of the data (only one day) to get a glimpse
# into the JSON structure that will be returned
r = requests.get('https://www.quandl.com/api/v3/datasets/FSE/AFX_X.json?start_date=2017-01-01&end_date=2017-01-02&api_key=WFJLtaGfefmVvsDu7iG8')

In [ ]:
# Inspect the JSON structure of the object you created, and take note of how nested it is,
# as well as the overall structure

These are your tasks for this mini project:

1. Collect data from the Franfurt Stock Exchange, for the ticker AFX_X, for the whole year 2017 (keep in mind that the date format is YYYY-MM-DD).
2. Convert the returned JSON object into a Python dictionary.
3. Calculate what the highest and lowest opening prices were for the stock in this period.
4. What was the largest change in any one day (based on High and Low price)?
5. What was the largest change between any two days (based on Closing Price)?
6. What was the average daily trading volume during this year?
7. (Optional) What was the median trading volume during this year. (Note: you may need to implement your own function for calculating the median.)

In [172]:
#Q1
r = requests.get('https://www.quandl.com/api/v3/datasets/FSE/AFX_X.json?start_date=2017-01-01&end_date=2017-12-31&api_key=WFJLtaGfefmVvsDu7iG8')
json_data = r.json()
json_data

{'dataset': {'id': 10095370,
  'dataset_code': 'AFX_X',
  'database_code': 'FSE',
  'name': 'Carl Zeiss Meditec (AFX_X)',
  'description': 'Stock Prices for Carl Zeiss Meditec (AFX) from the Frankfurt Stock Exchange.<br><br>Trading System: Xetra<br><br>ISIN: DE0005313704',
  'refreshed_at': '2019-01-24T22:30:49.665Z',
  'newest_available_date': '2019-01-24',
  'oldest_available_date': '2000-06-07',
  'column_names': ['Date',
   'Open',
   'High',
   'Low',
   'Close',
   'Change',
   'Traded Volume',
   'Turnover',
   'Last Price of the Day',
   'Daily Traded Units',
   'Daily Turnover'],
  'frequency': 'daily',
  'type': 'Time Series',
  'premium': False,
  'limit': None,
  'transform': None,
  'column_index': None,
  'start_date': '2017-01-01',
  'end_date': '2017-12-31',
  'data': [['2017-12-29',
    51.76,
    51.94,
    51.45,
    51.76,
    None,
    34640.0,
    1792304.0,
    None,
    None,
    None],
   ['2017-12-28',
    51.65,
    51.82,
    51.43,
    51.6,
    None,
    40660.0,
    2099024.0,
    None,
    None,
    None],
   ['2017-12-27',
    51.45,
    51.89,
    50.76,
    51.82,
    None,
    57452.0,
    2957018.0,
    None,
    None,
    None],
   ['2017-12-22',
    51.05,
    51.5,
    50.92,
    51.32,
    None,
    71165.0,
    3641949.0,
    None,
    None,
    None],
   ['2017-12-21',
    51.16,
    51.52,
    50.9,
    51.4,
    None,
    120649.0,
    6179433.0,
    None,
    None,
    None],
   ['2017-12-20',
    51.88,
    52.04,
    51.2,
    51.27,
    None,
    50587.0,
    2610258.0,
    None,
    None,
    None],
   ['2017-12-19',
    52.73,
    52.73,
    51.07,
    51.66,
    None,
    137313.0,
    7102361.0,
    None,
    None,
    None],
   ['2017-12-18',
    52.37,
    52.75,
    51.61,
    52.62,
    None,
    129733.0,
    6770499.0,
    None,
    None,
    None],
   ['2017-12-15',
    52.7,
    52.7,
    51.64,
    52.01,
    None,
    204080.0,
    10596319.0,
    None,
    None,
    None],
   ['2017-12-14',
    53.11,
    53.54,
    52.15,
    52.67,
    None,
    132981.0,
    7016953.0,
    None,
    None,
    None],
   ['2017-12-13',
    52.64,
    53.35,
    52.48,
    53.09,
    None,
    128434.0,
    6801159.0,
    None,
    None,
    None],
   ['2017-12-12',
    52.29,
    53.1,
    51.82,
    52.43,
    None,
    87911.0,
    4615924.0,
    None,
    None,
    None],
   ['2017-12-11',
    52.28,
    52.45,
    51.26,
    52.14,
    None,
    71817.0,
    3724193.0,
    None,
    None,
    None],
   ['2017-12-08',
    51.5,
    52.83,
    51.28,
    52.12,
    None,
    109157.0,
    5690648.0,
    None,
    None,
    None],
   ['2017-12-07',
    50.89,
    51.47,
    50.81,
    51.47,
    None,
    48123.0,
    2463848.0,
    None,
    None,
    None],
   ['2017-12-06',
    50.8,
    51.11,
    50.39,
    50.89,
    None,
    88730.0,
    4504075.0,
    None,
    None,
    None],
   ['2017-12-05',
    51.21,
    51.38,
    50.4,
    51.25,
    None,
    83023.0,
    4231971.0,
    None,
    None,
    None],
   ['2017-12-04',
    49.5,
    51.23,
    49.5,
    51.14,
    None,
    94385.0,
    4800027.0,
    None,
    None,
    None],
   ['2017-12-01',
    49.52,
    50.49,
    49.17,
    49.86,
    None,
    101733.0,
    5065932.0,
    None,
    None,
    None],
   ['2017-11-30',
    48.64,
    49.84,
    48.28,
    49.7,
    None,
    123019.0,
    6085171.0,
    None,
    None,
    None],
   ['2017-11-29',
    49.64,
    49.64,
    48.7,
    48.75,
    None,
    67342.0,
    3292223.0,
    None,
    None,
    None],
   ['2017-11-28',
    49.09,
    49.89,
    49.03,
    49.25,
    None,
    42669.0,
    2107358.0,
    None,
    None,
    None],
   ['2017-11-27',
    49.13,
    49.73,
    48.96,
    49.2,
    None,
    102180.0,
    5055762.0,
    None,
    None,
    None],
   ['2017-11-24',
    49.11,
    49.41,
    48.87,
    49.11,
    None,
    50350.0,
    2472842.0,
    None,
    None,
    None],
   ['2017-11-23',
    48.8,
    49.46,
    48.45,
    49.2,
    None,
    38834.0,
    1909352.0,
    None,
    None,
    None],
   ['2017-11-22',
    48.4,
    49.61,
    48.39,
    48.8,
    None,
    91142.0,
    4478093.0,
    None,
    None,
    None],
   ['2017-11-21',
    47.25,
    48.59,
    46.78,
    48.39,
    None,
    78502.0,
    3782098.0,
    None,
    None,
    None],
   ['2017-11-20',
    46.57,
    47.38,
    46.54,
    47.04,
    None,
    97252.0,
    4563515.0,
    None,
    None,
    None],
   ['2017-11-17',
    47.03,
    47.15,
    46.8,
    46.84,
    None,
    54107.0,
    2540820.0,
    None,
    None,
    None],
   ['2017-11-16',
    47.09,
    47.23,
    46.55,
    47.03,
    None,
    89373.0,
    4195732.0,
    None,
    None,
    None],
   ['2017-11-15',
    47.98,
    48.01,
    46.75,
    47.05,
    None,
    67593.0,
    3188321.0,
    None,
    None,
    None],
   ['2017-11-14',
    48.4,
    48.9,
    47.84,
    48.0,
    None,
    67672.0,
    3259979.0,
    None,
    None,
    None],
   ['2017-11-13',
    48.38,
    48.61,
    47.76,
    48.34,
    None,
    76286.0,
    3681337.0,
    None,
    None,
    None],
   ['2017-11-10',
    47.3,
    48.89,
    47.16,
    48.34,
    None,
    90245.0,
    4361552.0,
    None,
    None,
    None],
   ['2017-11-09',
    47.65,
    48.06,
    47.09,
    47.21,
    None,
    120268.0,
    5712034.0,
    None,
    None,
    None],
   ['2017-11-08',
    46.42,
    47.72,
    46.42,
    47.47,
    None,
    94195.0,
    4463935.0,
    None,
    None,
    None],
   ['2017-11-07',
    46.16,
    46.33,
    45.84,
    46.26,
    None,
    48152.0,
    2224221.0,
    None,
    None,
    None],
   ['2017-11-06',
    45.81,
    46.09,
    45.76,
    45.99,
    None,
    60716.0,
    2789220.0,
    None,
    None,
    None],
   ['2017-11-03',
    45.0,
    46.04,
    44.83,
    45.97,
    None,
    56911.0,
    2603498.0,
    None,
    None,
    None],
   ['2017-11-02',
    45.88,
    46.06,
    45.18,
    45.27,
    None,
    37958.0,
    1724840.0,
    None,
    None,
    None],
   ['2017-11-01',
    46.29,
    46.55,
    45.97,
    46.04,
    None,
    56319.0,
    2603859.0,
    None,
    None,
    None],
   ['2017-10-30',
    46.53,
    46.65,
    45.61,
    45.76,
    None,
    56245.0,
    2585397.0,
    None,
    None,
    None],
   ['2017-10-27',
    45.48,
    46.42,
    45.46,
    46.41,
    None,
    74472.0,
    3434087.0,
    None,
    None,
    None],
   ['2017-10-26',
    45.2,
    45.41,
    44.91,
    45.41,
    None,
    56319.0,
    2548078.0,
    None,
    None,
    None],
   ['2017-10-25',
    45.01,
    45.06,
    44.7,
    45.0,
    None,
    47730.0,
    2145697.0,
    None,
    None,
    None],
   ['2017-10-24',
    45.16,
    45.27,
    44.75,
    44.85,
    None,
    43042.0,
    1937616.0,
    None,
    None,
    None],
   ['2017-10-23',
    44.9,
    45.34,
    44.89,
    45.0,
    None,
    43375.0,
    1952918.0,
    None,
    None,
    None],
   ['2017-10-20',
    45.08,
    45.34,
    44.76,
    44.87,
    None,
    55707.0,
    2503853.0,
    None,
    None,
    None],
   ['2017-10-19',
    45.72,
    45.85,
    44.79,
    45.0,
    None,
    59991.0,
    2703085.0,
    None,
    None,
    None],
   ['2017-10-18',
    46.01,
    46.2,
    45.61,
    45.77,
    None,
    45263.0,
    2076951.0,
    None,
    None,
    None],
   ['2017-10-17',
    45.8,
    46.06,
    45.37,
    45.96,
    None,
    65837.0,
    3014080.0,
    None,
    None,
    None],
   ['2017-10-16',
    45.61,
    45.75,
    45.3,
    45.55,
    None,
    49246.0,
    2243129.0,
    None,
    None,
    None],
   ['2017-10-13',
    45.5,
    45.7,
    45.37,
    45.4,
    None,
    43362.0,
    1971801.0,
    None,
    None,
    None],
   ['2017-10-12',
    45.58,
    45.58,
    45.17,
    45.43,
    None,
    49180.0,
    2233481.0,
    None,
    None,
    None],
   ['2017-10-11',
    45.97,
    45.97,
    45.25,
    45.29,
    None,
    69455.0,
    3158321.0,
    None,
    None,
    None],
   ['2017-10-10',
    45.64,
    46.04,
    45.57,
    45.84,
    None,
    65860.0,
    3016658.0,
    None,
    None,
    None],
   ['2017-10-09',
    46.2,
    46.2,
    45.6,
    45.74,
    None,
    44059.0,
    2015453.0,
    None,
    None,
    None],
   ['2017-10-06',
    46.19,
    46.19,
    45.69,
    46.0,
    None,
    66760.0,
    3066198.0,
    None,
    None,
    None],
   ['2017-10-05',
    46.01,
    46.09,
    45.63,
    46.05,
    None,
    94804.0,
    4352002.0,
    None,
    None,
    None],
   ['2017-10-04',
    45.36,
    46.17,
    45.22,
    46.11,
    None,
    115706.0,
    5313199.0,
    None,
    None,
    None],
   ['2017-10-02',
    44.51,
    44.98,
    44.18,
    44.98,
    None,
    95313.0,
    4265024.0,
    None,
    None,
    None],
   ['2017-09-29',
    43.58,
    44.17,
    43.3,
    44.17,
    None,
    99821.0,
    4384796.0,
    None,
    None,
    None],
   ['2017-09-28',
    42.0,
    43.56,
    42.0,
    43.56,
    None,
    157234.0,
    6775569.0,
    None,
    None,
    None],
   ['2017-09-27',
    42.35,
    42.49,
    41.78,
    42.04,
    None,
    76600.0,
    3219861.0,
    None,
    None,
    None],
   ['2017-09-26',
    42.3,
    42.57,
    42.11,
    42.37,
    None,
    51321.0,
    2175381.0,
    None,
    None,
    None],
   ['2017-09-25',
    42.3,
    42.3,
    41.96,
    42.07,
    None,
    56224.0,
    2366453.0,
    None,
    None,
    None],
   ['2017-09-22',
    41.48,
    42.38,
    41.48,
    42.06,
    None,
    79955.0,
    3362517.0,
    None,
    None,
    None],
   ['2017-09-21',
    42.29,
    42.29,
    41.39,
    41.46,
    None,
    105194.0,
    4378409.0,
    None,
    None,
    None],
   ['2017-09-20',
    42.54,
    42.54,
    41.99,
    41.99,
    None,
    57838.0,
    2440557.0,
    None,
    None,
    None],
   ['2017-09-19',
    42.65,
    42.65,
    42.13,
    42.44,
    None,
    65546.0,
    2777065.0,
    None,
    None,
    None],
   ['2017-09-18',
    42.5,
    42.63,
    42.23,
    42.27,
    None,
    44037.0,
    1864954.0,
    None,
    None,
    None],
   ['2017-09-15',
    42.29,
    42.81,
    42.25,
    42.42,
    None,
    107144.0,
    4555791.0,
    None,
    None,
    None],
   ['2017-09-14',
    42.35,
    42.8,
    42.35,
    42.52,
    None,
    65157.0,
    2770696.0,
    None,
    None,
    None],
   ['2017-09-13',
    42.49,
    42.69,
    42.22,
    42.45,
    None,
    68801.0,
    2921240.0,
    None,
    None,
    None],
   ['2017-09-12',
    43.21,
    43.34,
    42.62,
    42.73,
    None,
    52828.0,
    2259924.0,
    None,
    None,
    None],
   ['2017-09-11',
    42.81,
    42.89,
    42.56,
    42.85,
    None,
    103273.0,
    4415614.0,
    None,
    None,
    None],
   ['2017-09-08',
    42.7,
    42.75,
    42.56,
    42.67,
    None,
    59881.0,
    2553977.0,
    None,
    None,
    None],
   ['2017-09-07',
    43.0,
    43.02,
    42.67,
    42.77,
    None,
    64320.0,
    2751388.0,
    None,
    None,
    None],
   ['2017-09-06',
    42.66,
    42.71,
    42.34,
    42.55,
    None,
    71006.0,
    3020229.0,
    None,
    None,
    None],
   ['2017-09-05',
    43.0,
    43.19,
    42.55,
    42.62,
    None,
    66351.0,
    2846115.0,
    None,
    None,
    None],
   ['2017-09-04',
    42.38,
    42.75,
    41.95,
    42.6,
    None,
    105288.0,
    4471634.0,
    None,
    None,
    None],
   ['2017-09-01',
    42.16,
    43.06,
    42.07,
    42.41,
    None,
    151474.0,
    6453558.0,
    None,
    None,
    None],
   ['2017-08-31',
    42.0,
    42.08,
    41.12,
    41.9,
    None,
    157888.0,
    6580200.0,
    None,
    None,
    None],
   ['2017-08-30',
    42.0,
    42.2,
    41.49,
    41.94,
    None,
    97804.0,
    4090262.0,
    None,
    None,
    None],
   ['2017-08-29',
    41.71,
    41.98,
    41.33,
    41.85,
    None,
    98156.0,
    4094452.0,
    None,
    None,
    None],
   ['2017-08-28',
    42.11,
    42.25,
    41.86,
    41.91,
    None,
    47130.0,
    1978704.0,
    None,
    None,
    None],
   ['2017-08-25',
    42.64,
    42.64,
    42.05,
    42.14,
    None,
    69734.0,
    2948016.0,
    None,
    None,
    None],
   ['2017-08-24',
    42.72,
    43.05,
    42.63,
    42.69,
    None,
    65213.0,
    2792319.0,
    None,
    None,
    None],
   ['2017-08-23',
    42.82,
    43.17,
    42.6,
    42.71,
    None,
    70269.0,
    3011578.0,
    None,
    None,
    None],
   ['2017-08-22',
    42.46,
    42.96,
    42.4,
    42.71,
    None,
    95376.0,
    4075646.0,
    None,
    None,
    None],
   ['2017-08-21',
    42.42,
    42.76,
    42.2,
    42.26,
    None,
    68812.0,
    2922972.0,
    None,
    None,
    None],
   ['2017-08-18',
    42.28,
    42.6,
    42.01,
    42.41,
    None,
    72886.0,
    3092377.0,
    None,
    None,
    None],
   ['2017-08-17',
    41.88,
    43.01,
    41.76,
    42.5,
    None,
    131361.0,
    5583704.0,
    None,
    None,
    None],
   ['2017-08-16',
    42.4,
    42.62,
    41.98,
    42.05,
    None,
    104676.0,
    4408312.0,
    None,
    None,
    None],
   ['2017-08-15',
    42.53,
    42.53,
    42.2,
    42.28,
    None,
    64334.0,
    2721852.0,
    None,
    None,
    None],
   ['2017-08-14',
    42.12,
    42.69,
    42.01,
    42.3,
    None,
    127682.0,
    5416963.0,
    None,
    None,
    None],
   ['2017-08-11',
    41.3,
    41.94,
    40.96,
    41.94,
    None,
    183412.0,
    7604144.0,
    None,
    None,
    None],
   ['2017-08-10',
    41.73,
    41.99,
    41.14,
    41.68,
    None,
    175161.0,
    7303562.0,
    None,
    None,
    None],
   ['2017-08-09',
    43.5,
    43.5,
    41.64,
    41.81,
    None,
    355857.0,
    15003956.0,
    None,
    None,
    None],
   ['2017-08-08',
    44.9,
    45.09,
    44.15,
    44.37,
    None,
    156168.0,
    6941408.0,
    None,
    None,
    None],
   ['2017-08-07',
    45.85,
    46.34,
    44.02,
    44.96,
    None,
    164543.0,
    7378816.0,
    None,
    None,
    None],
   ['2017-08-04',
    45.13,
    45.13,
    44.36,
    45.07,
    None,
    96202.0,
    4306911.0,
    None,
    None,
    None],
   ['2017-08-03',
    45.34,
    45.54,
    44.91,
    44.97,
    None,
    77854.0,
    3517146.0,
    None,
    None,
    None],
   ['2017-08-02',
    45.25,
    45.77,
    44.9,
    45.56,
    None,
    187468.0,
    8528548.0,
    None,
    None,
    None],
   ['2017-08-01',
    45.24,
    45.54,
    45.1,
    45.45,
    None,
    74975.0,
    3399891.0,
    None,
    None,
    None],
   ['2017-07-31',
    44.94,
    45.75,
    44.94,
    45.3,
    None,
    62672.0,
    2844210.0,
    None,
    None,
    None],
   ['2017-07-28',
    45.26,
    45.29,
    44.75,
    44.97,
    None,
    114006.0,
    5127247.0,
    None,
    None,
    None],
   ['2017-07-27',
    45.16,
    45.45,
    45.15,
    45.25,
    None,
    50557.0,
    2290284.0,
    None,
    None,
    None],
   ['2017-07-26',
    44.91,
    45.33,
    44.46,
    45.16,
    None,
    81970.0,
    3688510.0,
    None,
    None,
    None],
   ['2017-07-25',
    44.7,
    45.04,
    44.63,
    44.82,
    None,
    112224.0,
    5033312.0,
    None,
    None,
    None],
   ['2017-07-24',
    45.31,
    45.31,
    44.49,
    44.61,
    None,
    104282.0,
    4661866.0,
    None,
    None,
    None],
   ['2017-07-21',
    45.57,
    45.88,
    45.04,
    45.44,
    None,
    73422.0,
    3334695.0,
    None,
    None,
    None],
   ['2017-07-20',
    45.74,
    45.96,
    45.23,
    45.66,
    None,
    87399.0,
    3986488.0,
    None,
    None,
    None],
   ['2017-07-19',
    45.06,
    45.72,
    44.94,
    45.57,
    None,
    71971.0,
    3273001.0,
    None,
    None,
    None],
   ['2017-07-18',
    45.5,
    45.55,
    44.7,
    45.0,
    None,
    104003.0,
    4684627.0,
    None,
    None,
    None],
   ['2017-07-17',
    45.6,
    46.23,
    45.29,
    45.6,
    None,
    104995.0,
    4801806.0,
    None,
    None,
    None],
   ['2017-07-14',
    45.07,
    45.56,
    44.83,
    45.53,
    None,
    67375.0,
    3054060.0,
    None,
    None,
    None],
   ['2017-07-13',
    44.67,
    45.18,
    44.67,
    44.95,
    None,
    82745.0,
    3718928.0,
    None,
    None,
    None],
   ['2017-07-12',
    44.29,
    45.05,
    43.89,
    44.95,
    None,
    115705.0,
    5133971.0,
    None,
    None,
    None],
   ['2017-07-11',
    44.94,
    44.94,
    44.08,
    44.2,
    None,
    90538.0,
    4010457.0,
    None,
    None,
    None],
   ['2017-07-10',
    44.64,
    45.18,
    44.51,
    44.7,
    None,
    71868.0,
    3221218.0,
    None,
    None,
    None],
   ['2017-07-07',
    44.79,
    44.79,
    44.25,
    44.53,
    None,
    47999.0,
    2136578.0,
    None,
    None,
    None],
   ['2017-07-06',
    45.5,
    45.5,
    44.15,
    44.62,
    None,
    66116.0,
    2952605.0,
    None,
    None,
    None],
   ['2017-07-05',
    44.67,
    45.36,
    44.44,
    45.19,
    None,
    48706.0,
    2189436.0,
    None,
    None,
    None],
   ['2017-07-04',
    45.83,
    45.83,
    44.74,
    44.8,
    None,
    50549.0,
    2273551.0,
    None,
    None,
    None],
   ['2017-07-03',
    45.29,
    45.83,
    45.06,
    45.75,
    None,
    71381.0,
    3251502.0,
    None,
    None,
    None],
   ['2017-06-30',
    45.01,
    45.74,
    45.0,
    45.44,
    None,
    136112.0,
    6187148.0,
    None,
    None,
    None],
   ['2017-06-29',
    45.73,
    45.81,
    45.11,
    45.2,
    None,
    134965.0,
    6132452.0,
    None,
    None,
    None],
   ['2017-06-28',
    46.68,
    46.68,
    45.41,
    45.68,
    None,
    117165.0,
    5381488.0,
    None,
    None,
    None],
   ['2017-06-27',
    47.23,
    47.33,
    46.39,
    46.83,
    None,
    82492.0,
    3866344.0,
    None,
    None,
    None],
   ['2017-06-26',
    46.95,
    47.63,
    46.91,
    47.21,
    None,
    73322.0,
    3465639.0,
    None,
    None,
    None],
   ['2017-06-23',
    47.29,
    47.4,
    46.79,
    46.99,
    None,
    80586.0,
    3792498.0,
    None,
    None,
    None],
   ['2017-06-22',
    47.03,
    47.4,
    46.75,
    47.29,
    None,
    56071.0,
    2640508.0,
    None,
    None,
    None],
   ['2017-06-21',
    47.46,
    47.48,
    46.53,
    46.99,
    None,
    89752.0,
    4206563.0,
    None,
    None,
    None],
   ['2017-06-20',
    46.48,
    47.43,
    46.27,
    47.37,
    None,
    108334.0,
    5109730.0,
    None,
    None,
    None],
   ['2017-06-19',
    46.9,
    46.9,
    46.25,
    46.64,
    None,
    70056.0,
    3260381.0,
    None,
    None,
    None],
   ['2017-06-16',
    45.66,
    46.8,
    45.66,
    46.63,
    None,
    202214.0,
    9411695.0,
    None,
    None,
    None],
   ['2017-06-15',
    46.34,
    46.34,
    45.21,
    45.67,
    None,
    101733.0,
    4635593.0,
    None,
    None,
    None],
   ['2017-06-14',
    46.52,
    46.86,
    46.05,
    46.33,
    None,
    83741.0,
    3881453.0,
    None,
    None,
    None],
   ['2017-06-13',
    46.5,
    46.51,
    46.03,
    46.32,
    None,
    107644.0,
    4981185.0,
    None,
    None,
    None],
   ['2017-06-12',
    47.31,
    47.43,
    45.89,
    46.31,
    None,
    112942.0,
    5238390.0,
    None,
    None,
    None],
   ['2017-06-09',
    46.77,
    47.44,
    46.55,
    47.44,
    None,
    99674.0,
    4702170.0,
    None,
    None,
    None],
   ['2017-06-08',
    47.8,
    47.8,
    46.27,
    46.27,
    None,
    1945.0,
    90599.0,
    None,
    None,
    None],
   ['2017-06-07',
    47.01,
    47.43,
    47.01,
    47.43,
    None,
    1081.0,
    51021.0,
    None,
    None,
    None],
   ['2017-06-06',
    47.12,
    47.45,
    46.21,
    47.43,
    None,
    686.0,
    32083.0,
    None,
    None,
    None],
   ['2017-06-02',
    46.8,
    46.99,
    46.72,
    46.99,
    None,
    290.0,
    13584.0,
    None,
    None,
    None],
   ['2017-06-01',
    46.12,
    46.52,
    45.89,
    46.52,
    None,
    106513.0,
    4930686.0,
    None,
    None,
    None],

In [173]:
#Q2
#Access data portion of JSON file and convert to dataframe
python_data = json_data['dataset']['data']
python_data = pd.DataFrame(python_data)
python_data.columns=['Date', 'Open', 'High', 'Low', 'Close', 'Change', 'Traded Volume', 'Turnover', 'Last Price of the Day', 'Daily Traded Units', 'Daily Turnover']
python_data

,Date,Open,High,Low,Close,Change,Traded Volume,Turnover,Last Price of the Day,Daily Traded Units,Daily Turnover
0,2017-12-29,51.76,51.94,51.45,51.76,NaN,34640.0,1792304.0,None,None,None
1,2017-12-28,51.65,51.82,51.43,51.60,NaN,40660.0,2099024.0,None,None,None
2,2017-12-27,51.45,51.89,50.76,51.82,NaN,57452.0,2957018.0,None,None,None
3,2017-12-22,51.05,51.50,50.92,51.32,NaN,71165.0,3641949.0,None,None,None
4,2017-12-21,51.16,51.52,50.90,51.40,NaN,120649.0,6179433.0,None,None,None
5,2017-12-20,51.88,52.04,51.20,51.27,NaN,50587.0,2610258.0,None,None,None
6,2017-12-19,52.73,52.73,51.07,51.66,NaN,137313.0,7102361.0,None,None,None
7,2017-12-18,52.37,52.75,51.61,52.62,NaN,129733.0,6770499.0,None,None,None
8,2017-12-15,52.70,52.70,51.64,52.01,NaN,204080.0,10596319.0,None,None,None
9,2017-12-14,53.11,53.54,52.15,52.67,NaN,132981.0,7016953.0,None,None,None
10,2017-12-13,52.64,53.35,52.48,53.09,NaN,128434.0,6801159.0,None,None,None
11,2017-12-12,52.29,53.10,51.82,52.43,NaN,87911.0,4615924.0,None,None,None
12,2017-12-11,52.28,52.45,51.26,52.14,NaN,71817.0,3724193.0,None,None,None
13,2017-12-08,51.50,52.83,51.28,52.12,NaN,109157.0,5690648.0,None,None,None
14,2017-12-07,50.89,51.47,50.81,51.47,NaN,48123.0,2463848.0,None,None,None
15,2017-12-06,50.80,51.11,50.39,50.89,NaN,88730.0,4504075.0,None,None,None
16,2017-12-05,51.21,51.38,50.40,51.25,NaN,83023.0,4231971.0,None,None,None
17,2017-12-04,49.50,51.23,49.50,51.14,NaN,94385.0,4800027.0,None,None,None
18,2017-12-01,49.52,50.49,49.17,49.86,NaN,101733.0,5065932.0,None,None,None
19,2017-11-30,48.64,49.84,48.28,49.70,NaN,123019.0,6085171.0,None,None,None
20,2017-11-29,49.64,49.64,48.70,48.75,NaN,67342.0,3292223.0,None,None,None
21,2017-11-28,49.09,49.89,49.03,49.25,NaN,42669.0,2107358.0,None,None,None
22,2017-11-27,49.13,49.73,48.96,49.20,NaN,102180.0,5055762.0,None,None,None
23,2017-11-24,49.11,49.41,48.87,49.11,NaN,50350.0,2472842.0,None,None,None
24,2017-11-23,48.80,49.46,48.45,49.20,NaN,38834.0,1909352.0,None,None,None
25,2017-11-22,48.40,49.61,48.39,48.80,NaN,91142.0,4478093.0,None,None,None
26,2017-11-21,47.25,48.59,46.78,48.39,NaN,78502.0,3782098.0,None,None,None
27,2017-11-20,46.57,47.38,46.54,47.04,NaN,97252.0,4563515.0,None,None,None
28,2017-11-17,47.03,47.15,46.80,46.84,NaN,54107.0,2540820.0,None,None,None
29,2017-11-16,47.09,47.23,46.55,47.03,NaN,89373.0,4195732.0,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...
225,2017-02-10,36.65,37.50,36.57,37.06,NaN,115843.0,4291017.0,None,None,None
226,2017-02-09,36.20,36.25,35.77,36.25,NaN,67781.0,2445428.0,None,None,None
227,2017-02-08,35.98,36.14,35.84,36.05,NaN,39731.0,1431205.0,None,None,None
228,2017-02-07,35.56,36.05,35.36,35.89,NaN,67410.0,2410818.0,None,None,None
229,2017-02-06,36.06,36.15,35.60,35.64,NaN,41911.0,1496794.0,None,None,None
230,2017-02-03,36.02,36.20,35.73,36.10,NaN,40705.0,1464712.0,None,None,None
231,2017-02-02,35.95,36.20,35.70,36.07,NaN,54279.0,1953176.0,None,None,None
232,2017-02-01,34.75,36.00,34.75,35.94,NaN,85137.0,3038172.0,None,None,None
233,2017-01-31,35.24,35.24,34.56,34.56,NaN,63371.0,2199583.0,None,None,None
234,2017-01-30,35.38,35.59,34.95,35.15,NaN,69603.0,2457762.0,None,None,None
235,2017-01-27,34.83,35.43,34.81,35.30,NaN,69657.0,2444913.0,None,None,None
236,2017-01-26,35.07,35.58,34.80,34.89,NaN,64103.0,2249375.0,None,None,None
237,2017-01-25,34.42,34.86,34.03,34.83,NaN,56240.0,1947147.0,None,None,None
238,2017-01-24,34.00,34.35,33.85,34.22,NaN,48797.0,1666086.0,None,None,None
239,2017-01-23,34.04,34.12,33.62,34.06,NaN,55333.0,1877957.0,None,None,None
240,2017-01-20,34.54,34.59,34.05,34.17,NaN,80246.0,2743474.0,None,None,None
241,2017-01-19,35.04,35.04,34.42,34.50,NaN,73105.0,2526731.0,None,None,None
242,2017-01-18,35.04,35.51,34.80,34.90,NaN,65931.0,2311608.0,None,None,None
243,2017-01-17,35.06,35.19,34.79,34.99,NaN,39195.0,1369857.0,None,None,None
244,2017-01-16,34.85,35.24,34.56,35.07,NaN,47879.0,1678679.0,None,None,None
245,2017-01-13,34.98,34.98,34.60,34.85,NaN,59367.0,2065534.0,None,None,None
246,2017-01-12,35.38,35.38,34.31,34.90,NaN,163860.0,5703427.0,None,None,None
247,2017-01-11,34.95,36.00,34.84,35.42,NaN,123530.0,4369079.0,None,None,None
248,2017-01-10,34.80,34.98,34.46,34.91,NaN,43976.0,1528055.0,None,None,None
249,2017-01-09,35.29,35.35,34.43,34.67,NaN,62225.0,2157182.0,None,None,None
250,2017-01-06,34.91,35.21,34.91,35.04,NaN,27507.0,964046.0,None,None,None
251,2017-01-05,35.02,35.20,34.73,35.06,NaN,48412.0,1692326.0,None,None,None
252,2017-01-04,35.48,35.51,34.75,35.19,NaN,54408.0,1906810.0,None,None,None
253,2017-01-03,35.90,35.93,35.34,35.48,NaN,70618.0,2515473.0,None,None,None
254,2017-01-02,34.99,35.94,34.99,35.80,NaN,44700.0,1590561.0,None,None,None

In [174]:
python_data['Open'].idxmax()

9

In [175]:
python_data['Open'].idxmin()

238

In [176]:
#Q3 Print the maximum and minimum opening price
open_max = python_data.iloc[[9]]
print(open_max)
open_min = python_data.iloc[[238]]
print(open_min)

         Date   Open   High    Low  Close  Change  Traded Volume   Turnover  \
9  2017-12-14  53.11  53.54  52.15  52.67     NaN       132981.0  7016953.0

  Last Price of the Day Daily Traded Units Daily Turnover
9                  None               None           None
           Date  Open   High    Low  Close  Change  Traded Volume   Turnover  \
238  2017-01-24  34.0  34.35  33.85  34.22     NaN        48797.0  1666086.0

    Last Price of the Day Daily Traded Units Daily Turnover
238                  None               None           None

In [177]:
#Fills in 'Change' column with the difference between the High and Low prices
python_data['Change'] = python_data['High'] - python_data['Low']

In [178]:
python_data

,Date,Open,High,Low,Close,Change,Traded Volume,Turnover,Last Price of the Day,Daily Traded Units,Daily Turnover
0,2017-12-29,51.76,51.94,51.45,51.76,0.49,34640.0,1792304.0,None,None,None
1,2017-12-28,51.65,51.82,51.43,51.60,0.39,40660.0,2099024.0,None,None,None
2,2017-12-27,51.45,51.89,50.76,51.82,1.13,57452.0,2957018.0,None,None,None
3,2017-12-22,51.05,51.50,50.92,51.32,0.58,71165.0,3641949.0,None,None,None
4,2017-12-21,51.16,51.52,50.90,51.40,0.62,120649.0,6179433.0,None,None,None
5,2017-12-20,51.88,52.04,51.20,51.27,0.84,50587.0,2610258.0,None,None,None
6,2017-12-19,52.73,52.73,51.07,51.66,1.66,137313.0,7102361.0,None,None,None
7,2017-12-18,52.37,52.75,51.61,52.62,1.14,129733.0,6770499.0,None,None,None
8,2017-12-15,52.70,52.70,51.64,52.01,1.06,204080.0,10596319.0,None,None,None
9,2017-12-14,53.11,53.54,52.15,52.67,1.39,132981.0,7016953.0,None,None,None
10,2017-12-13,52.64,53.35,52.48,53.09,0.87,128434.0,6801159.0,None,None,None
11,2017-12-12,52.29,53.10,51.82,52.43,1.28,87911.0,4615924.0,None,None,None
12,2017-12-11,52.28,52.45,51.26,52.14,1.19,71817.0,3724193.0,None,None,None
13,2017-12-08,51.50,52.83,51.28,52.12,1.55,109157.0,5690648.0,None,None,None
14,2017-12-07,50.89,51.47,50.81,51.47,0.66,48123.0,2463848.0,None,None,None
15,2017-12-06,50.80,51.11,50.39,50.89,0.72,88730.0,4504075.0,None,None,None
16,2017-12-05,51.21,51.38,50.40,51.25,0.98,83023.0,4231971.0,None,None,None
17,2017-12-04,49.50,51.23,49.50,51.14,1.73,94385.0,4800027.0,None,None,None
18,2017-12-01,49.52,50.49,49.17,49.86,1.32,101733.0,5065932.0,None,None,None
19,2017-11-30,48.64,49.84,48.28,49.70,1.56,123019.0,6085171.0,None,None,None
20,2017-11-29,49.64,49.64,48.70,48.75,0.94,67342.0,3292223.0,None,None,None
21,2017-11-28,49.09,49.89,49.03,49.25,0.86,42669.0,2107358.0,None,None,None
22,2017-11-27,49.13,49.73,48.96,49.20,0.77,102180.0,5055762.0,None,None,None
23,2017-11-24,49.11,49.41,48.87,49.11,0.54,50350.0,2472842.0,None,None,None
24,2017-11-23,48.80,49.46,48.45,49.20,1.01,38834.0,1909352.0,None,None,None
25,2017-11-22,48.40,49.61,48.39,48.80,1.22,91142.0,4478093.0,None,None,None
26,2017-11-21,47.25,48.59,46.78,48.39,1.81,78502.0,3782098.0,None,None,None
27,2017-11-20,46.57,47.38,46.54,47.04,0.84,97252.0,4563515.0,None,None,None
28,2017-11-17,47.03,47.15,46.80,46.84,0.35,54107.0,2540820.0,None,None,None
29,2017-11-16,47.09,47.23,46.55,47.03,0.68,89373.0,4195732.0,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...
225,2017-02-10,36.65,37.50,36.57,37.06,0.93,115843.0,4291017.0,None,None,None
226,2017-02-09,36.20,36.25,35.77,36.25,0.48,67781.0,2445428.0,None,None,None
227,2017-02-08,35.98,36.14,35.84,36.05,0.30,39731.0,1431205.0,None,None,None
228,2017-02-07,35.56,36.05,35.36,35.89,0.69,67410.0,2410818.0,None,None,None
229,2017-02-06,36.06,36.15,35.60,35.64,0.55,41911.0,1496794.0,None,None,None
230,2017-02-03,36.02,36.20,35.73,36.10,0.47,40705.0,1464712.0,None,None,None
231,2017-02-02,35.95,36.20,35.70,36.07,0.50,54279.0,1953176.0,None,None,None
232,2017-02-01,34.75,36.00,34.75,35.94,1.25,85137.0,3038172.0,None,None,None
233,2017-01-31,35.24,35.24,34.56,34.56,0.68,63371.0,2199583.0,None,None,None
234,2017-01-30,35.38,35.59,34.95,35.15,0.64,69603.0,2457762.0,None,None,None
235,2017-01-27,34.83,35.43,34.81,35.30,0.62,69657.0,2444913.0,None,None,None
236,2017-01-26,35.07,35.58,34.80,34.89,0.78,64103.0,2249375.0,None,None,None
237,2017-01-25,34.42,34.86,34.03,34.83,0.83,56240.0,1947147.0,None,None,None
238,2017-01-24,34.00,34.35,33.85,34.22,0.50,48797.0,1666086.0,None,None,None
239,2017-01-23,34.04,34.12,33.62,34.06,0.50,55333.0,1877957.0,None,None,None
240,2017-01-20,34.54,34.59,34.05,34.17,0.54,80246.0,2743474.0,None,None,None
241,2017-01-19,35.04,35.04,34.42,34.50,0.62,73105.0,2526731.0,None,None,None
242,2017-01-18,35.04,35.51,34.80,34.90,0.71,65931.0,2311608.0,None,None,None
243,2017-01-17,35.06,35.19,34.79,34.99,0.40,39195.0,1369857.0,None,None,None
244,2017-01-16,34.85,35.24,34.56,35.07,0.68,47879.0,1678679.0,None,None,None
245,2017-01-13,34.98,34.98,34.60,34.85,0.38,59367.0,2065534.0,None,None,None
246,2017-01-12,35.38,35.38,34.31,34.90,1.07,163860.0,5703427.0,None,None,None
247,2017-01-11,34.95,36.00,34.84,35.42,1.16,123530.0,4369079.0,None,None,None
248,2017-01-10,34.80,34.98,34.46,34.91,0.52,43976.0,1528055.0,None,None,None
249,2017-01-09,35.29,35.35,34.43,34.67,0.92,62225.0,2157182.0,None,None,None
250,2017-01-06,34.91,35.21,34.91,35.04,0.30,27507.0,964046.0,None,None,None
251,2017-01-05,35.02,35.20,34.73,35.06,0.47,48412.0,1692326.0,None,None,None
252,2017-01-04,35.48,35.51,34.75,35.19,0.76,54408.0,1906810.0,None,None,None
253,2017-01-03,35.90,35.93,35.34,35.48,0.59,70618.0,2515473.0,None,None,None
254,2017-01-02,34.99,35.94,34.99,35.80,0.95,44700.0,1590561.0,None,None,None

In [179]:
#Q4 What was the largest change in any one day (based on High and Low price)?
python_data['Change'].idxmax()

161

In [180]:
max_change = python_data.iloc[[161]]
print(max_change)

           Date  Open   High    Low  Close  Change  Traded Volume   Turnover  \
161  2017-05-11  43.4  46.06  43.25   45.0    2.81       189125.0  8496322.0

    Last Price of the Day Daily Traded Units Daily Turnover
161                  None               None           None

In [181]:
#Creates a new column "Closing Price Diff" that shows the change between any two days, based on Closing Price
python_data['Closing Price Diff'] = python_data['Close'].diff()
python_data

,Date,Open,High,Low,Close,Change,Traded Volume,Turnover,Last Price of the Day,Daily Traded Units,Daily Turnover,Closing Price Diff
0,2017-12-29,51.76,51.94,51.45,51.76,0.49,34640.0,1792304.0,None,None,None,NaN
1,2017-12-28,51.65,51.82,51.43,51.60,0.39,40660.0,2099024.0,None,None,None,-0.16
2,2017-12-27,51.45,51.89,50.76,51.82,1.13,57452.0,2957018.0,None,None,None,0.22
3,2017-12-22,51.05,51.50,50.92,51.32,0.58,71165.0,3641949.0,None,None,None,-0.50
4,2017-12-21,51.16,51.52,50.90,51.40,0.62,120649.0,6179433.0,None,None,None,0.08
5,2017-12-20,51.88,52.04,51.20,51.27,0.84,50587.0,2610258.0,None,None,None,-0.13
6,2017-12-19,52.73,52.73,51.07,51.66,1.66,137313.0,7102361.0,None,None,None,0.39
7,2017-12-18,52.37,52.75,51.61,52.62,1.14,129733.0,6770499.0,None,None,None,0.96
8,2017-12-15,52.70,52.70,51.64,52.01,1.06,204080.0,10596319.0,None,None,None,-0.61
9,2017-12-14,53.11,53.54,52.15,52.67,1.39,132981.0,7016953.0,None,None,None,0.66
10,2017-12-13,52.64,53.35,52.48,53.09,0.87,128434.0,6801159.0,None,None,None,0.42
11,2017-12-12,52.29,53.10,51.82,52.43,1.28,87911.0,4615924.0,None,None,None,-0.66
12,2017-12-11,52.28,52.45,51.26,52.14,1.19,71817.0,3724193.0,None,None,None,-0.29
13,2017-12-08,51.50,52.83,51.28,52.12,1.55,109157.0,5690648.0,None,None,None,-0.02
14,2017-12-07,50.89,51.47,50.81,51.47,0.66,48123.0,2463848.0,None,None,None,-0.65
15,2017-12-06,50.80,51.11,50.39,50.89,0.72,88730.0,4504075.0,None,None,None,-0.58
16,2017-12-05,51.21,51.38,50.40,51.25,0.98,83023.0,4231971.0,None,None,None,0.36
17,2017-12-04,49.50,51.23,49.50,51.14,1.73,94385.0,4800027.0,None,None,None,-0.11
18,2017-12-01,49.52,50.49,49.17,49.86,1.32,101733.0,5065932.0,None,None,None,-1.28
19,2017-11-30,48.64,49.84,48.28,49.70,1.56,123019.0,6085171.0,None,None,None,-0.16
20,2017-11-29,49.64,49.64,48.70,48.75,0.94,67342.0,3292223.0,None,None,None,-0.95
21,2017-11-28,49.09,49.89,49.03,49.25,0.86,42669.0,2107358.0,None,None,None,0.50
22,2017-11-27,49.13,49.73,48.96,49.20,0.77,102180.0,5055762.0,None,None,None,-0.05
23,2017-11-24,49.11,49.41,48.87,49.11,0.54,50350.0,2472842.0,None,None,None,-0.09
24,2017-11-23,48.80,49.46,48.45,49.20,1.01,38834.0,1909352.0,None,None,None,0.09
25,2017-11-22,48.40,49.61,48.39,48.80,1.22,91142.0,4478093.0,None,None,None,-0.40
26,2017-11-21,47.25,48.59,46.78,48.39,1.81,78502.0,3782098.0,None,None,None,-0.41
27,2017-11-20,46.57,47.38,46.54,47.04,0.84,97252.0,4563515.0,None,None,None,-1.35
28,2017-11-17,47.03,47.15,46.80,46.84,0.35,54107.0,2540820.0,None,None,None,-0.20
29,2017-11-16,47.09,47.23,46.55,47.03,0.68,89373.0,4195732.0,None,None,None,0.19
...,...,...,...,...,...,...,...,...,...,...,...,...
225,2017-02-10,36.65,37.50,36.57,37.06,0.93,115843.0,4291017.0,None,None,None,-1.47
226,2017-02-09,36.20,36.25,35.77,36.25,0.48,67781.0,2445428.0,None,None,None,-0.81
227,2017-02-08,35.98,36.14,35.84,36.05,0.30,39731.0,1431205.0,None,None,None,-0.20
228,2017-02-07,35.56,36.05,35.36,35.89,0.69,67410.0,2410818.0,None,None,None,-0.16
229,2017-02-06,36.06,36.15,35.60,35.64,0.55,41911.0,1496794.0,None,None,None,-0.25
230,2017-02-03,36.02,36.20,35.73,36.10,0.47,40705.0,1464712.0,None,None,None,0.46
231,2017-02-02,35.95,36.20,35.70,36.07,0.50,54279.0,1953176.0,None,None,None,-0.03
232,2017-02-01,34.75,36.00,34.75,35.94,1.25,85137.0,3038172.0,None,None,None,-0.13
233,2017-01-31,35.24,35.24,34.56,34.56,0.68,63371.0,2199583.0,None,None,None,-1.38
234,2017-01-30,35.38,35.59,34.95,35.15,0.64,69603.0,2457762.0,None,None,None,0.59
235,2017-01-27,34.83,35.43,34.81,35.30,0.62,69657.0,2444913.0,None,None,None,0.15
236,2017-01-26,35.07,35.58,34.80,34.89,0.78,64103.0,2249375.0,None,None,None,-0.41
237,2017-01-25,34.42,34.86,34.03,34.83,0.83,56240.0,1947147.0,None,None,None,-0.06
238,2017-01-24,34.00,34.35,33.85,34.22,0.50,48797.0,1666086.0,None,None,None,-0.61
239,2017-01-23,34.04,34.12,33.62,34.06,0.50,55333.0,1877957.0,None,None,None,-0.16
240,2017-01-20,34.54,34.59,34.05,34.17,0.54,80246.0,2743474.0,None,None,None,0.11
241,2017-01-19,35.04,35.04,34.42,34.50,0.62,73105.0,2526731.0,None,None,None,0.33
242,2017-01-18,35.04,35.51,34.80,34.90,0.71,65931.0,2311608.0,None,None,None,0.40
243,2017-01-17,35.06,35.19,34.79,34.99,0.40,39195.0,1369857.0,None,None,None,0.09
244,2017-01-16,34.85,35.24,34.56,35.07,0.68,47879.0,1678679.0,None,None,None,0.08
245,2017-01-13,34.98,34.98,34.60,34.85,0.38,59367.0,2065534.0,None,None,None,-0.22
246,2017-01-12,35.38,35.38,34.31,34.90,1.07,163860.0,5703427.0,None,None,None,0.05
247,2017-01-11,34.95,36.00,34.84,35.42,1.16,123530.0,4369079.0,None,None,None,0.52
248,2017-01-10,34.80,34.98,34.46,34.91,0.52,43976.0,1528055.0,None,None,None,-0.51
249,2017-01-09,35.29,35.35,34.43,34.67,0.92,62225.0,2157182.0,None,None,None,-0.24
250,2017-01-06,34.91,35.21,34.91,35.04,0.30,27507.0,964046.0,None,None,None,0.37
251,2017-01-05,35.02,35.20,34.73,35.06,0.47,48412.0,1692326.0,None,None,None,0.02
252,2017-01-04,35.48,35.51,34.75,35.19,0.76,54408.0,1906810.0,None,None,None,0.13
253,2017-01-03,35.90,35.93,35.34,35.48,0.59,70618.0,2515473.0,None,None,None,0.29
254,2017-01-02,34.99,35.94,34.99,35.80,0.95,44700.0,1590561.0,None,None,None,0.32

In [182]:
#Locates the index for the max Closing Price Diff value
python_data['Closing Price Diff'].idxmax()

99

In [183]:
#Q5: What was the largest change between any two days (based on Closing Price)?
#Prints the row corresponding to max Closing Price Diff value
max_close_diff = python_data.iloc[[99]]
print(max_close_diff)

          Date  Open   High    Low  Close  Change  Traded Volume   Turnover  \
99  2017-08-08  44.9  45.09  44.15  44.37    0.94       156168.0  6941408.0

   Last Price of the Day Daily Traded Units Daily Turnover  Closing Price Diff
99                  None               None           None                2.56

In [185]:
#Q6 What was the average daily trading volume during this year?
#Calculates the mean 
python_data['Traded Volume'].mean()

89124.33725490196